import { CommunityReview } from '../types/trip';

export const REVIEWS: CommunityReview[] = [
  {
    id: 'rev-1',
    destination: 'Goa',
    authorName: 'Rohan Deshmukh',
    authorRole: 'Student Traveler • IIT Bombay',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    rating: 4.9,
    reviewText: 'Chapora fort sunset is pure magic and totally free! We rented scooters for ₹350/day and ate at local fish thali spots in Mapusa for ₹140. Best student budget trip ever generated by SmartTrip AI.',
    date: '2 days ago',
    category: 'Hidden Gems',
    tags: ['#HiddenGem', '#Sunset', '#StudentBudget', '#ScooterTrip'],
    likesCount: 142,
    hasLiked: false
  },
  {
    id: 'rev-2',
    destination: 'Goa',
    authorName: 'Pooja & Sameer Sen',
    authorRole: 'Couple • Bangalore',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    rating: 4.8,
    reviewText: 'Fontainhas Latin Quarter walk felt like walking in Lisbon. Take photos between 3 PM and 5 PM when the light hits the yellow and indigo walls. Try the warm poi bread at 31 de Janeiro bakery.',
    date: '4 days ago',
    category: 'Activities',
    tags: ['#PortugueseHeritage', '#LatinQuarter', '#CoupleTravel', '#Foodie'],
    likesCount: 89,
    hasLiked: false
  },
  {
    id: 'rev-3',
    destination: 'Manali',
    authorName: 'Vikram Joshi',
    authorRole: 'Solo Backpacker • Delhi',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    rating: 5.0,
    reviewText: 'Jogini waterfall trek is 100x more serene than crowded Solang. Follow the pine forest trail from Vashisht temple. The water mist is crystal cold. SmartTrip weather adaptation saved me from a sudden rain shower!',
    date: '1 week ago',
    category: 'Hidden Gems',
    tags: ['#JoginiTrek', '#SoloTraveler', '#NatureVibes', '#PineForest'],
    likesCount: 215,
    hasLiked: false
  },
  {
    id: 'rev-4',
    destination: 'Jaipur',
    authorName: 'Ananya Sharma',
    authorRole: 'Family Explorer • Pune',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    rating: 4.7,
    reviewText: 'Amer fort audio guides are very kid-friendly. We skipped the rush hour by booking 8:30 AM slot. Wind View Cafe rooftop opposite Hawa Mahal has the best view for evening samosa chai with family.',
    date: '2 weeks ago',
    category: 'Safety',
    tags: ['#FamilyTrip', '#AmerFort', '#KidFriendly', '#SafeTravel'],
    likesCount: 76,
    hasLiked: false
  },
  {
    id: 'rev-5',
    destination: 'Kerala',
    authorName: 'Dr. Arvind Menon',
    authorRole: 'Nature Lover • Chennai',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 4.9,
    reviewText: 'Small canoe tours through Kuttanad backwaters get into tiny water canals that giant houseboats can never reach. You see kingfishers and local village life up close. Outstanding recommendation!',
    date: '2 weeks ago',
    category: 'Activities',
    tags: ['#Backwaters', '#EcoTourism', '#Serenity', '#KeralaVibes'],
    likesCount: 164,
    hasLiked: false
  },
  {
    id: 'rev-6',
    destination: 'Rishikesh',
    authorName: 'Tanya Mehta',
    authorRole: 'Adventure Enthusiast • Mumbai',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 4.8,
    reviewText: 'Shivpuri 16km rafting with cliff jumping gave me goosebumps! Book early morning slot at 8 AM because the water is pristine and rapids are energetic. Evening Ganga Aarti at Triveni gave me goosebumps of peace.',
    date: '3 weeks ago',
    category: 'Activities',
    tags: ['#WhiteWaterRafting', '#CliffJumping', '#GangaAarti', '#Thrill'],
    likesCount: 198,
    hasLiked: false
  }
];
